### ISSUE TITLE
help_text suggests that current password appears in a data breach

### ISSUE THREAD

**Issue by mimi89999** [lionheart/django-pwnedpasswords-validator#3]
_Your password has previously appeared in a data breach and should never be used._ is shown under the _New password_ field.

![capture du 2018-03-07 20-31-25](https://user-images.githubusercontent.com/8530546/37113739-8938c166-2246-11e8-86ed-de63447dd87e.png)

> get_help_text(): provide a help text to explain the requirements to the user.

get_help_text() should be used to describe the rule. It is not the error text.

**Comment by mimi89999** [comment]
https://github.com/Pawamoy/django-zxcvbn-password/issues/46

**Comment by dlo** [comment]
I modeled it after the other `get_help_text` return values from the built-in validators. The current value explains what the validator does, which is what I think the text is supposed to do. Happy to reopen if you have a suggestion for improvement.

**Comment by dlo** [comment]
Now that I'm reading how it appears in the admin, I take that back. It can be better.

**Comment by dlo** [comment]
@mimi89999 check out the change in 5f74fff and let me know what you think

**Comment by mimi89999** [comment]
Why do you use the word `previously`? I think it is not needed.

**Comment by mimi89999** [comment]
I wonder what would @troyhunt put under the _New password_ field.

**Comment by dlo** [comment]
Troy, you're welcome to submit a PR :)
